min_epoch: 1
max_epoch: 10

min_learning_rate: 0.001
max_learning_rate: 1

min_momentum: 0.1
max_momentum: 0.90

batch_size: 4
min_batch: 2
max_batch: 100

epochs: 1

# since the CIFAR dataset has a built in test/train set, we don't need 
# to define a value for the ratio of test images. Instead we are going to split
# the train set into train and validation sets
validation_ratio: 0.1
train_ratio: 0.9
